FROM node:23-alpine

USER root

WORKDIR /frontend_react

COPY ./frontend_react/package.json .
COPY ./frontend_react/package-lock.json .

RUN npm install

COPY ./frontend_react .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"] 
# ポート番号3000